name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up JDK 11 (required for Android builds)
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    # Step 3: Install Android SDK command line tools and build environment
    - name: Install Android SDK
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip
        wget https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip
        unzip commandlinetools-linux-7583922_latest.zip -d $HOME/Android
        yes | $HOME/Android/cmdline-tools/bin/sdkmanager --sdk_root=$HOME/Android --licenses
        $HOME/Android/cmdline-tools/bin/sdkmanager --sdk_root=$HOME/Android "platform-tools" "platforms;android-30" "build-tools;30.0.3"

    # Step 4: Build APK using Gradle
    - name: Build APK
      run: |
        cd rootbeer
        ./gradlew assembleRelease

    # Step 5: Upload the APK as an artifact
    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: rootbeer-apk
        path: rootbeer/app/build/outputs/apk/release/app-release.apk
